---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow direct updates for all packages
      - dependency-type: "direct"
    assignees:
      - "vyasknellutla"
    reviewers:
      - "vyasknellutla"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow direct updates for all packages
      - dependency-type: "direct"
    assignees:
      - "vyasknellutla"
    reviewers:
      - "vyasknellutla"
